apiVersion: araft/v1
kind: Deployment
metadata:
  name: araft
spec:
  selector:
    matchLabels:
      app: araft
  replicas: 3
  template:
    metadata:
      labels:
        app: araft
    spec:
      containers:
      - name: araft
        image: mgurdal/araft:latest
        ports:
        - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: araft
spec:
  selector:
    app: araft
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 30001
  type: NodePort
