# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import raft_pb2 as raft__pb2


class RaftServiceStub(object):
  """RaftService implements the raft pipelining receiver.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AppendEntries = channel.unary_unary(
        '/RaftService/AppendEntries',
        request_serializer=raft__pb2.AppendEntriesRequest.SerializeToString,
        response_deserializer=raft__pb2.AppendEntriesResponse.FromString,
        )
    self.RequestVote = channel.unary_unary(
        '/RaftService/RequestVote',
        request_serializer=raft__pb2.RequestVoteRequest.SerializeToString,
        response_deserializer=raft__pb2.RequestVoteResponse.FromString,
        )


class RaftServiceServicer(object):
  """RaftService implements the raft pipelining receiver.
  """

  def AppendEntries(self, request, context):
    """AppendEntries performs a single append entries request / response.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestVote(self, request, context):
    """RequestVote is the command used by a candidate to ask a Raft peer for a vote in an election.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RaftServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AppendEntries': grpc.unary_unary_rpc_method_handler(
          servicer.AppendEntries,
          request_deserializer=raft__pb2.AppendEntriesRequest.FromString,
          response_serializer=raft__pb2.AppendEntriesResponse.SerializeToString,
      ),
      'RequestVote': grpc.unary_unary_rpc_method_handler(
          servicer.RequestVote,
          request_deserializer=raft__pb2.RequestVoteRequest.FromString,
          response_serializer=raft__pb2.RequestVoteResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'RaftService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
